// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nvvinjzzfbwjxswpslos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52dmluanp6ZmJ3anhzd3BzbG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NTg1ODMsImV4cCI6MjA4NzAzNDU4M30.kAha5n2O-ZZIm7_tMi0Tue16kjq6FWxImSj8RrCnweo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);